export const REPORT_HTML_CLASSES = [
  'report-dashboard',
  'report-metrics',
  'report-metric',
  'report-metric-label',
  'report-metric-value',
  'report-metric-delta',
  'report-findings',
  'report-finding',
  'report-finding-attention',
  'report-finding-positive',
  'report-finding-neutral',
  'report-finding-title',
  'report-evidence',
  'report-note',
  'report-citation',
  'report-table',
] as const;

export const REPORT_HTML_TAGS = [
  'h2',
  'h3',
  'p',
  'strong',
  'b',
  'em',
  'a',
  'ul',
  'ol',
  'li',
  'table',
  'thead',
  'tbody',
  'tr',
  'th',
  'td',
  'div',
  'section',
  'span',
] as const;
